/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_helloworld_android_HelloJNI */

#ifndef _Included_com_example_helloworld_android_HelloJNI
#define _Included_com_example_helloworld_android_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_helloworld_android_HelloJNI
 * Method:    HelloNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_helloworld_1android_HelloJNI_HelloNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
